config/routes.rb
Rails.application.routes.draw do

  get 'listings/index'
  get 'listings/show'
  get 'listings/new'
  get 'listings/create'
  get 'listings/edit'
  get 'listings/update'
  get 'static_pages/home'
  get 'static_pages/help'

  resources :listings do
    resources :reservations, only:[:create]
  end
  root 'titles#index'
  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }

  resources :titles
  resources :listings
  resources :users
  resources :photos, only: [:create, :destroy]
  root to: "home#index"

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/acount' => 'listings#acount', as: 'manage_listing_acount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:update]

  def index
    @listings = current_user.listings
  end

  def show
    @listing = Listing.find(params[:id])
    @photos = @listing.photos
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      redirect_to manage_listing_basics_path(@listing), notice: "リスティングを作成・保存をしました"
    else
      redirect_to new_listing_path, notice: "リスティングを作成・保存出来ませんでした"
    end

  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_back(fallback_location: root_path)
    end
  end

  def basics
    @listing = Listing.find(params[:id])
  end

  def description
    @listing = Listing.find(params[:id])
  end

  def address
    @listing = Listing.find(params[:id])
  end

  def price
    @listing = Listing.find(params[:id])
  end

  def photos
    @listing = Listing.find(params[:id])
    @photo = Photo.new
  end

  def calendar
    @listing = Listing.find(params[:id])
  end

  def acount
    @listing = Listing.find(params[:id])
  end

  def publish
    @listing = Listing.find(params[:id])
  end

  private
  def listing_params
    params.require(:listing).permit(:home_type, :pet_type, :breeding_years, :pet_size, :price_pernight, :price, :address, :address, :listing_title, :listing_content, :active)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_navibar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active" if contoller?("listings") && action?("basics") %>
          <%= link_to "基本事項", manage_listing_basics_path(@listing) %>
        </li>
        <li class="active" if contoller?("listings") && action?("basics") %>
          <%= link_to "募集の内容", manage_listing_description_path(@listing) %>
        </li>
        <li class="active" if contoller?("listings") && action?("basics") %>
          <%= link_to "住所情報", manage_listing_address_path(@listing) %>
        </li>
        <li class="active" if contoller?("listings") && action?("basics") %>
          <%= link_to "料金", manage_listing_price_path(@listing) %>
        </li>
        <li class="active" if contoller?("listings") && action?("basics") %>
          <%= link_to "写真情報", manage_listing_photos_path(@listing), data: { turbolinks: false }  %>
        </li>
        <li class="active" if contoller?("listings") && action?("basics") %>
        <li><%= link_to "カレンダー", manage_listing_calendar_path(@listing) %></li>
        <li><%= link_to "リスティング", listings_path(@listing) %></li>
        <li><%= link_to "口座情報", manage_listing_acount_path(@listing) %></li>
        <li><%= link_to "公開", manage_listing_publish_path(@listing) %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/listings/address.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'navibar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">住所の編集</span>
                </div>
            </div>

            <div class="panel-body">

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>住所</label>
                                <%= f.text_field :address, placeholder: "例: 東京都港区六本木６丁目１１−１", class: "form-control" %>
                            </div>
                        </div>

                    </div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/basics.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
<%= render "navibar" %>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              <div class="text-center">
                  <span style="font-size:24px;">基本データの編集</span>
              </div>
          </div>

          <div class="panel-body">
              <%= form_for @listing do |f| %>
                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>お家の種類</label>
                              <%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの種類</label>
                              <%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットの飼育歴</label>
                              <%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>ペットのサイズ</label>
                              <%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="actions">
                      <%= f.submit "更新", class: "btn btn-danger" %>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/description.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'navibar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング内容の編集</span>
                </div>
            </div>

            <div class="panel-body">

                <%= form_for @listing do |f| %>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>タイトル</label>
                                <%= f.text_field :listing_title, placeholder: "リスティングタイトルを記載しましょう", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>内容</label>
                                <%= f.text_area :listing_content, rows: 8, placeholder: "リスティングの内容について記述してください", class: "form-control" %>
                            </div>
                        </div>
                    </div>


                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<div class="container">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:18px;">リスティング一覧</span>
                </div>
            </div>
            <ul class="ul-unstyled">
                <% @listings.each do |listing| %>
                    <li class="panel-body">
                        <div class="row-table">
                            <div class="col-md-3 col-sm-3 col-middle row-space-2">
                                <div class="panel-list-img text-center">
                                    <%= image_tag listing.photos[0].image.url(:medium) if listing.photos.length > 0  %>
                                </div>
                            </div>

                            <div class="col-sm-7 col-lg-7 col-middle row-space-2">
                                <span class="listing-title"><%= listing.listing_title %></span>
                            </div>

                            <div class="col-md-3 col-sm-3 col-middle row-space-1">
                                <%= link_to "残り5ステップ", manage_listing_basics_path(listing), class: "btn btn-primary pull-right" %>
                            </div>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>

    </div>
</div>

app/views/listings/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="text-center">
						<span style="font-size:24px;">ペットリスティングを掲載する</span>
					</div>
				</div>

				<div class="panel-body">
					<!-- ここからフォーム -->
					<%= form_for @listing do |f| %>
						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>お家の種類</label>
									<%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットの種類</label>
									<%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットの飼育歴</label>
									<%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<label>ペットのサイズ</label>
									<%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
								</div>
							</div>
						</div>
						<br>

						<div class="actions">
							<%= f.submit "Save", class: "btn btn-danger" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>

</div>

app/views/listings/photos.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'navibar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">リスティング写真の編集</span>
                </div>
            </div>

            <div class="panel-body">
                <%= form_for @photo, html:{multipart: true,class:"dropzone", id:"my-dropzone" } do |f| %>

                    <div class="dz-message needsclick">
                        <h3>ファイルをここにドロップしてください。</h3>
                        <strong>アップロードするにはここをクリックしてください</strong>
                    </div>

                    <div class="fallback">
                        <%= f.file_field :image %>
                        <%= f.submit "Upload image" %>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/price.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'navibar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">料金の設定</span>
                </div>
            </div>

            <div class="panel-body">

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label>一泊あたりの料金</label>
                          <div class="input-group">
                            <div class="input-group-addon">円</div>
                            <%= f.text_field :price_pernight, placeholder: "例: 100", class: "form-control" %>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/publish.html.erb
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'navibar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="text-center">
                    <span style="font-size:24px;">公開する</span>
                </div>
            </div>

            <div class="panel-body">

                <%= form_for @listing do |f| %>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                            <%= f.select :active, [["公開する","true"], ["非公開にする","false"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                        </div>
                      </div>
                    </div>

                    <div class="actions">
                        <%= f.submit "更新", class: "btn btn-danger" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/listings/show.html.erb
<!-- ジャンボトロン -->
<div class="jumbotron row-space-0" style="margin-top: -20px; background: none;">

  <!-- カルーセル -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- リストの点 -->
    <% if @photos.length > 1 %>
      <ol class="carousel-indicators">
        <% @photos.each do |photo| %>
            <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
        <% end %>
      </ol>
    <% end %>

    <div class="carousel-inner" role="listbox">
      <% if @photos %>
        <% @photos.each do |photo| %>
          <div class="item <%= 'active' if photo.id == @photos[0].id %>">
            <%= image_tag photo.image.url(),style: "height:420px; width:100%; overflow:hidden;" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- 左右の矢印 -->
    <% if @photos.length > 1%>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    <% end %>
  </div>

</div>

<!-- サマリー -->
<div class="container-fluid container-listing-show">
    <div class="container">
        <div class="listing-summary row-space-3 row-space-top-3">
            <div class="row">
                <div class="col-md-3 text-center row-space-2">
                    <h5><%= @listing.user.name %></h5>
                </div>
                <div class="col-md-6">
                    <div class="listing-title" style="font-size:24px;">
                        <%= @listing.listing_title %>
                    </div>
                    <div class="row row-space-top-4">
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-home fa-3x"></i>
                            <h5><%= @listing.home_type %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-linux fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.pet_type %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-bug fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.pet_size %></h5>
                        </div>
                        <div class="col-sm-3 col-xs-3 text-center">
                            <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
                            <h5><%= @listing.breeding_years %>年</h5>
                        </div>
                    </div>
                </div>

                <!-- 予約フォーム -->
                <div class="col-md-3">
                    <div class="panel panel-default panel-show">
                        <div class="panel-heading">
                                <span style="font-size:16px;"><%= @listing.price_pernight %>円（一晩あたり）</span>
                        </div>

                        <div class="panel-body panel-real">
                            <%= form_for [@listing, @listing.reservations.new] do |f| %>

                                <!-- これは、予約をするときに、一緒におくる、データです。-->
                                <%= f.hidden_field :listing_id, value: @listing.id %>
                                <%= f.hidden_field :price_pernight, value: @listing.price_pernight %>
                                <%= f.hidden_field :total_price, id:'reservation_total_price' %>

                                <div class="row row-space-2">
                                    <div class="col-md-6">
                                        <label>Check In</label>
                                          <%= f.text_field :start_date, :class => 'form-control', placeholder: '開始' %>
                                    </div>

                                    <div class="col-md-6">
                                        <label>Check Out</label>
                                        <%= f.text_field :end_date, :class => 'form-control', placeholder: '終了' %>
                                    </div>
                                </div>

                                <div class="actions text-center">
                                    <%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- メインコンテント -->
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="row-space-3">このリスティングについて</h3>
                <p><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %>
                </p>
        </div>

        <div class="col-md-4">

        </div>
    </div>


    <!-- レビュー    -->
    <div class="row">
        <div class="col-md-8">
            <h3 class="row-space-3">このリスティングについて</h3>
            <p><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %><%= @listing.listing_content %></p>
        </div>

        <div class="col-md-4">
        </div>
    </div>
</div>

<script>
$( function() {
  $( "#datepicker" ).datepicker();
} );
</script>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>