config/routes.rb
Rails.application.routes.draw do

  get 'listings/index'
  get 'listings/show'
  get 'listings/new'
  get 'listings/create'
  get 'listings/edit'
  get 'listings/update'
  get 'static_pages/home'
  get 'static_pages/help'

  resources :listings do
    resources :reservations, only:[:create]
  end
  root 'titles#index'
  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }

  resources :titles
  resources :listings
  resources :users
  resources :photos, only: [:create, :destroy]
  root to: "home#index"

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/acount' => 'listings#acount', as: 'manage_listing_acount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/title.rb
class Title < ApplicationRecord
    mount_uploader :picture, PictureUploader
    default_scope -> { order(created_at: :desc) }
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]
  PER = 16
  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.page(params[:page]).per(PER)
    require 'open-uri'
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:memo, :author, :picture, :id, :tag, :tag2, :data)
    end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_with(model: title, local: true) do |form| %>
  <% if title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo, id: :title_memo %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :author, id: :title_author %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :title_picture %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag, id: :title_tag %>
  </div>
  <div class="field">
    <%= form.label :tag2 %>
    <%= form.text_field :tag2, id: :title_tag2 %>
  </div>
  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :title_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Show', @title %> |

<%= link_to 'Back', titles_path %>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Memo:</strong>
  <%= @title.memo %>
</p>

<p>
  <strong>Author:</strong>
  <%= @title.author %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@title.picture_url) if @title.picture.present? %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>