config/routes.rb
Rails.application.routes.draw do

  get 'listings/index'
  get 'listings/show'
  get 'listings/new'
  get 'listings/create'
  get 'listings/edit'
  get 'listings/update'
  get 'static_pages/home'
  get 'static_pages/help'

  resources :listings do
    resources :reservations, only:[:create]
  end
  root 'titles#index'
  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }

  resources :titles
  resources :listings
  resources :users
  resources :photos, only: [:create, :destroy]
  root to: "home#index"

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/acount' => 'listings#acount', as: 'manage_listing_acount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Photographer</title>
    <%= analytics_init if Rails.env.production? %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Your Photographer", '/', id: "logo" %>
        <nav>
          <ul class="nav-navbar-nav-navbar-right">
            <% if (!user_signed_in?) %>
              <li><%= link_to "login", new_user_session_path %></li>
              <li><%= link_to "make_acount", new_user_registration_path %></li>
            <% else %>
                  <% if current_user.provider %>
                    <%= image_tag current_user.image, class:"img-circle" %>
                    <% else %>
                    <%= current_user.email %>
                  <% end %>
    　        <li><%= link_to "make", new_listing_path %></li>
              <li><%= link_to "profile", user_path(current_user) %></li>
              <li><%= link_to "編集ページ", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% end %>
        </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>